### ISSUE TITLE
please allow typing-extensions>=4.6.0

### ISSUE THREAD

**Issue by comfuture** [MarshalX/atproto#102]
Many other packages depend on typing-extensions>=4.6.1.
Please consider supporting >=4.6.0 to avoid dependency conflicts.

**Comment by MarshalX** [comment]
I want but I can't because if this https://github.com/hashberg-io/dag-cbor/issues/12

**Comment by MarshalX** [comment]
I hope it will be fixed and ill update it too

**Comment by MarshalX** [comment]
the problematic deps were replaced by [ipld](https://github.com/MarshalX/python-libipld) in https://github.com/MarshalX/atproto/pull/127 

typing-extensions >= 4.6.0 is allowed. will be included in the next release
