### ISSUE TITLE
BadRequestError: 'Token could not be verified'

### ISSUE THREAD

**Issue by IamC8** [MarshalX/atproto#165]
Hi MarshalX. 
Strange new error since this morning:

```
from atproto import Client, models, exceptions

client = Client()
profile = client.login('handle', 'pwd')
try:
    res = client.com.atproto.server.get_account_invite_codes(
        models.ComAtprotoServerGetAccountInviteCodes.Params(
            createAvailable=True,
            includeUsed=True)
    )
except exceptions.BadRequestError as err:
    print(err)
```
It throws an error with status code 400
'InvalidToken'
'Token could not be verified'

I looked at https://atproto.blue/en/latest/namespace.html#atproto.xrpc_client.namespaces.sync_ns.ServerNamespace.get_account_invite_codes again, there is nothing about a token?

What am I missing?
Please help.

**Comment by MarshalX** [comment]
pls create discussions not issues https://github.com/MarshalX/atproto/discussions/categories/questions
