### ISSUE TITLE
.login() got an unexpected keyword argument 'aud'

### ISSUE THREAD

**Issue by FrancoisMB** [MarshalX/atproto#185]
**Describe the bug**

Everything was working fine, up until two days ago, when I got this error, without any change in my code:

```
Traceback (most recent call last):

  File ~\Anaconda3\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File my_script.py:41
    bsky.login(login=bsky_handle, password=bsky_password)

  File ~\Anaconda3\anaconda3\lib\site-packages\atproto\xrpc_client\client\client.py:74 in login
    session = self._get_and_set_session(login, password)

  File ~\Anaconda3\anaconda3\lib\site-packages\atproto\xrpc_client\client\client.py:40 in _get_and_set_session
    self._set_session(session)

  File ~\Anaconda3\anaconda3\lib\site-packages\atproto\xrpc_client\client\methods_mixin\session.py:68 in _set_session
    self._refresh_jwt_payload = get_jwt_payload(session.refresh_jwt)

  File ~\Anaconda3\anaconda3\lib\site-packages\atproto\xrpc_client\client\auth.py:18 in get_jwt_payload
    return JwtPayload(**plain_payload)

TypeError: __init__() got an unexpected keyword argument 'aud'
```

**To Reproduce**

```
from atproto import Client, models
bsky_handle = "mybskyaccount.bsky.social"
bsky_password = "xxxx-xxxx-xxxx-xxxx"
bsky = Client()
bsky.login(login=bsky_handle, password=bsky_password)
```

**Expected behavior**

Well, it should be able to connect 😄 

**Details**

- Operating system: Windows 10
- Node version: no idea?

**Additional context**

- I really don't know, it was working fine, until it wasn't anymore, without making any changes to my python setup, to my script or to my bluesky account. 
- I tried updating, but I have atproto v 0.0.29 already.
- I tried using another app password, same error.
- Neither my account nor my password contain "aud".

**Comment by FrancoisMB** [comment]
Sorry, just saw new version is 0.0.30. Updated and it's working again.

**Comment by MarshalX** [comment]
Well-detailed bug report! Thank you! But yeah it has been fixed already
