### ISSUE TITLE
Make models less strict

### ISSUE THREAD

**Issue by MarshalX** [MarshalX/atproto#204]
### Problem
Each change of lexicons (API schemes) **may** break SDK. This requires model regeneration (this is automated) and a new SDK release on PyPi (this is what i do manually). So, the old versions are dying after changes on the backend. 

From one side is good to support only the latest version and keep it updated. Because of the unstable state of the whole protocol. From another side, i understand my users. They want to write 1 simple script/bsky bot, run it, and forget about it, and consume the results. Without fixing it every few weeks.

One of the popular issues is adding new fields to the models. For example #201. Ofc could be problems with data types, etc, but it's too much to ignore. So let's think about how we can **fix unknown fields**. 

@tonycsoka did good research about it in #176 
highlight:
> Unexpected fields in data which otherwise conforms to the Lexicon **should be ignored**. When doing schema validation, they should be treated **at worst as warnings**. This is necessary to allow evolution of the schema by the controlling authority, and to be robust in the case of out-of-date Lexicons.

i want to continue it here

### Notes
- for record types, for example, Post, we allow unknown fields because of the architecture of the protocol itself. But, we are parsing such "extended" records as `dict`. To be more precise as [DotDict](https://atproto.blue/en/latest/atproto/atproto.xrpc_client.models.dot_dict.html). `DotDict` exists to unify the codebase of end users to work with SDK models (to be able to use dot notation always). 
- we can think about applying `DotDict` for each model instead of Record only. but it leads to problems with types. `isinstance` and so on. we have the [solution for Records](https://atproto.blue/en/latest/atproto/atproto.xrpc_client.models.utils.html#atproto.xrpc_client.models.utils.is_record_type), but for any model idk. 
- we don't want to just ignore unknown fields when parsing models. we should provide access to it. because we a not an official bsky application, we want to have access to raw protocol and extra data that it could have, not only that we possibly need for "rendering". SDK should be a tool for scripting and doing random stuff as well. 
- we want a solution that could be roll-backed to the strict mode easily 
- bsky team doesn't have a 100% answer for the future. read https://atproto.com/specs/lexicon#possible-future-changes

### Solution
1. we are using pydantic. so the possible solution is just to `allow` `extra` fields: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra
2. keep strict mode and just provide user-friendly exception like "pls update your SDK"; make updating of the lexicon in SDK more automatic (one approve click from SDK maintainers; we can setup CI to create pull requests and do new releases)

### Open questions for solution No. 1
- as i understand this is a temporal problem until a stable version of the protocol. because later they will care about versioning lexicons, etc.. so should we allow it now to disallow it in the future? 
- I'm afraid of type checks, especially in Unions. i try to use tagged unions whenever possible. Lexicon provides `$type` field to understand what is it. but idk will it cover all edge cases?
- after allowing extra fields the purpose of `DotDict` is gone. it could serve only for unknown records in the data repositories. Fine?
- will it occur undefined behaviors from old versions? when users will not understand what the magic is happening. now SDK raises exception SDK about forbidden extra fields and users come to GitHub and check if is there a new SDK version that fixes it. 
- should we add warnings to the log about extra fields? "maybe you are using outdated SDK because '...' field comes from the backend and doesn't exist in the local described model". These warnings should be enabled/disabled for the user

**Comment by max2pt0** [comment]
I can only speak in general terms as someone trying to learn ATProto who is using your library as a tool to do this and hasn't yet released anything but may do so shortly. 

Since ATProto is still evolving I need the tool to evolve with it. I don't consider anything I write to be something that can be forgotten and expected to work if the library or ATProto changes. Any process that can be done to gracefully manage changes so there is less breakage would be great but not too much at the expense of your time as the developer of the library. If I have to code extra steps now to facilitate this process and know there will eventually be a one time change (?) when ATProto (and the library) is finalized that's fine by me.

**Comment by MarshalX** [comment]
new note. if we allow extra fields it will not help to detect such bugs of bsky https://github.com/MarshalX/atproto/issues/205. probably that's why this bug wasn't reported because they ignore "detailed" fields. and our SDK helps the third time to bsky team to fix bugs related to lexicon

**Comment by MarshalX** [comment]
> Lexicons are allowed to change over time, within some bounds to ensure both forwards and backwards compatibility. The basic principle is that all old data must still be valid under the updated Lexicon, and new data must be valid under the old Lexicon.

> - Any new fields must be optional
> - Non-optional fields can not be removed.
> - Types can not change
> - Fields can not be renamed

From here: https://atproto.com/specs/lexicon#lexicon-evolution

the first item confirms that we should make extra fields optional; the other 3 items confirms that others strict checks must be still enabled

**Comment by MarshalX** [comment]
Okay, I decided to do it. #207 brings:
- Allowing additional fields with access to it
- Warn on found additional field(s) with explanation why it could happen
- Ability to disable warn via env var (for now, maybe in the code later)
- Unit tests that cover lexicon evolution from official docs. [tests](https://github.com/MarshalX/atproto/blob/c817e81f192b8c0b240761d43e7ce85aabbbbfda/tests/models/tests/test_changed_lexicon_compatability.py)
