### ISSUE TITLE
Python Version Depency Issue

### ISSUE THREAD

**Issue by hack13** [MarshalX/atproto#221]
https://github.com/MarshalX/atproto/blob/f55fea61550074028cbe2e3b978e020b47d9442e/pyproject.toml#L51C25-L51C25

Is this intended? I am not able to use Python 3.12 which is the latest stable?

```bash
The current project's supported Python range (>=3.12,<4.0) is not compatible with some of the required packages Python requirement:
  - atproto requires Python >=3.7.1,<3.13, so it will not be satisfied for Python >=3.13,<4.0
```

**Comment by MarshalX** [comment]
Hi. Pls specify that your project this <3.13 too

**Comment by hack13** [comment]
Sorry about that, closing as a my issue. only recently switched to poetry and getting the hang of its nuances
