### ISSUE TITLE
Misspelling in get_author_feed

### ISSUE THREAD

**Issue by snazzyfox** [MarshalX/atproto#276]
Using `client.get_author_feed` with the `filter=` option does not seem to have an effect.

```py
resp = await client.get_author_feed(user, filter="posts_no_replies", limit=10)
```

This code always seems to return the same set of posts regardless of what filter is set to. Capturing logs from httpx seems to point to that the actual api call being made is misspelled:

```
2024-02-16 17:41:41,285 httpx: HTTP Request: GET https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed?actor=snazzythefox.bsky.social&limit=10&fitler=posts_no_replies "HTTP/1.1 200 OK"
```

**Comment by MarshalX** [comment]
thank you for your report! this is a bug

1. to avoid such bugs in the future [i fixed aliases for pyright](https://github.com/MarshalX/atproto/pull/277). which now highlights such typos properly without false positives 

<img width="1107" alt="image" src="https://github.com/MarshalX/atproto/assets/15520314/a9788eea-0935-4574-a8c8-d21f62a6ee61">

2. this bug will be fixed today and i gonna release v0.0.42

**Comment by MarshalX** [comment]
released. pls update

**Comment by snazzyfox** [comment]
confirmed it's working properly in the latest release; appreciate the quick fix!
