### ISSUE TITLE
Subscribing to feed?

### ISSUE THREAD

**Issue by lokxii** [MarshalX/atproto#282]
There are examples to subscribe firehose and process events. Is there anyway to subscribe to a feed instead? Are there any docs / example showing how to do so?

**Comment by MarshalX** [comment]
Hi, check this https://www.docs.bsky.app/docs/tutorials/viewing-feeds#feed-generators. Press on the "Python" tab to see examples

**Comment by MarshalX** [comment]
No custom feeds doesn't create events in firehose. This is not possible to subscribe to updates. Custom feeds are independent services out of PDS

**Comment by lokxii** [comment]
Thx for the reply! I guess I have rethink how my project is going to work
