### ISSUE TITLE
Failing on authentication

### ISSUE THREAD

**Issue by mshea** [MarshalX/atproto#319]
My Bluesky script stopped working and now kicks back this error:

`raise ModelError(str(e)) from e
atproto.exceptions.ModelError: 1 validation error for Response
emailAuthFactor
  Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden`

Did Bluesky change how one authenticates?

**Comment by MarshalX** [comment]
Could you share versions of atproto lib that you are using?

**Comment by mshea** [comment]
Sorry, yeah, I was using an old version. 0.46 works!

**Comment by mshea** [comment]
User error!
