### ISSUE TITLE
client.com.atproto.repo.describe_repo stopped working in atproto==0.0.49

### ISSUE THREAD

**Issue by emilyhunt** [MarshalX/atproto#379]
When trying to use [`client.com.atproto.repo.describe_repo`](https://atproto.blue/en/latest/atproto_client/namespace.html#atproto_client.namespaces.sync_ns.ComAtprotoRepoNamespace.describe_repo), from atproto==0.049 onwards & with Python 3.12.1, I get the following error, for multiple different DIDs:

```
BadRequestError: Response(success=False, status_code=400, content=XrpcError(error='RepoNotFound', message='Could not find repo for DID: did:plc:jcoy7v3a2t4rcfdh6i4kza25'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-remaining': '2993', 'ratelimit-reset': '1725272140', 'ratelimit-policy': '3000;w=300', 'content-type': 'application/json; charset=utf-8', 'content-length': '98', 'etag': 'W/"62-CG83jMd+MVjPpLUk0Afdz4DlUTc"', 'vary': 'Accept-Encoding', 'date': 'Mon, 02 Sep 2024 10:15:29 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})
```

Full traceback: [traceback.txt](https://github.com/user-attachments/files/16836196/traceback.txt)
Contents of pip list for my test with atproto==0.0.49: [requirements.txt](https://github.com/user-attachments/files/16836220/requirements.txt)

The following code should reproduce the bug:

```
from atproto import client, models

client = Client()
client.login(...)  # Add your details here
params = models.com.atproto.repo.describe_repo.Params(repo="did:plc:jcoy7v3a2t4rcfdh6i4kza25")
client.com.atproto.repo.describe_repo(params)
```

I tested this code in atproto==0.0.48 (where it worked), in atproto==0.0.49 (where it doesn't work), and also in atproto==0.0.52 (doesn't work).

Thanks!

**Comment by emilyhunt** [comment]
(P.S. this isn't urgent as `atproto.IdResolver` works for what I need and that seems to be fine)

**Comment by MarshalX** [comment]
> Could not find repo for DID: did:plc:jcoy7v3a2t4rcfdh6i4kza25

did you switch to proper PDS (where this DID is hosted) before calling `describe_repo`?

**Comment by emilyhunt** [comment]
It's possible that's the problem, but I'm not sure - the code above still works right now with atproto==0.0.48 (which was released June 1st, way after multiple PDSes were implemented). 

#188 references a method in `atproto.sync`, whereas this is in `atproto.repo` - not sure if that matters.

How... _do_ you switch PDS with the client? The parameters model for the method [only has a repo argument](https://atproto.blue/en/latest/atproto/atproto_client.models.com.atproto.repo.describe_repo.html#atproto_client.models.com.atproto.repo.describe_repo.Params), so I'm not sure how to do that. (Sorry!)

**Comment by MarshalX** [comment]
Hmm... This is because the "main" bsky PDS is just a proxy to many other PDS... so it can automatically choose the right one. This proxy was in use before 0.0.48, right. But this is not the best way how to deal with it imho.

This is pseudo-code:
```python
did = 'did:123'
resolver = ....
resolved_did = resolve.resolve(did)

client = Client(base_url=resolved_did.get_pds_endpoint())
repo = cllient.describe_repo(did)
print(repo)
```

**Comment by MarshalX** [comment]
probably it could be a cool feature to disable pds auto switching

**Comment by MarshalX** [comment]
hi @emilyhunt! do you expect any further work here or we could close it?

**Comment by emilyhunt** [comment]
Can be closed!
