### ISSUE TITLE
Get ratelimit info before reaching limit

### ISSUE THREAD

**Issue by Linus2punkt0** [MarshalX/atproto#401]
Bluesky have recently gotten really aggressive with their ratelimit, is it possible to get information about ratelimit-remaining and ratelimit-reset before actually reaching the limit?

**Comment by MarshalX** [comment]
Duplicates https://github.com/MarshalX/atproto/discussions/286 ?

**Comment by Linus2punkt0** [comment]
Yes, thank you, that seems to be all that I need!
