### ISSUE TITLE
How to get response headers (specifically to get rate limits)?

### ISSUE THREAD

**Issue by ariok** [MarshalX/atproto#414]
When I call a function on the client, which is the best way to access the headers for the generated HTTP response?
```python
client.like(post.uri, post.cid)
# how to get the response headers of the previous call considering that this call is returning just a 'CreateRecordResponse'

```
I'd like to get info about the rate limit that from my understanding are only available from the response headers.

**Comment by MarshalX** [comment]
hi, duplicated? https://github.com/MarshalX/atproto/discussions/167#discussioncomment-8579573

**Comment by ariok** [comment]
> hi, duplicated? [#167 (comment)](https://github.com/MarshalX/atproto/discussions/167#discussioncomment-8579573)

Yes, definitely a duplicate.
