### ISSUE TITLE
pydantic Field (or something else?) not allowing newline characters to pass on and create new lines

### ISSUE THREAD

**Issue by s-ivr** [MarshalX/atproto#448]
ex:
client.send_post('look\nat\nme", langs=['en-US'])

should (IMO) post as:
look
at
me

but instead posts as:
look\nat\nme

the API supports that directly and that's how it handles newlines etc.

I haven't fiddled with pydantic fields much, so I wasn't sure why you went with them for the text string (not being critical, expressing my ignorance), and it may have nothing to do with them. Was following through the code a bit but then realized I had to get back to my day job so I wanted to ask you your thoughts.

Thanks!
.jason

**Comment by MarshalX** [comment]
```python
def main() -> None:
    client = Client()
    client.login(os.environ['USERNAME'], os.environ['PASSWORD'])

    client.send_post('test2\n\ntest2\n\ntest3')
```

it works for me very well; the post: https://bsky.app/profile/test.marshal.dev/post/3lbibjg3j5c2r

**Comment by s-ivr** [comment]
Lol. That's wild. 
I swear it didn't work in similar code before, but it must be zsh/MacOS doing something on the way in then when I try to take it from the command line. This fails with:
 ./post.py "test2\n\ntest2\n\ntest3"
 I love linux/unix/macOS but I'm guessing I've just stumbled onto a thing everyone else knows about with command line args but not me. I even tried it with input() and had the same problem. :/
 
 Thanks for your help!
--
client = Client()

load_dotenv()
user = os.getenv('USERNAME')
password = os.getenv('PW')
login_result = client.login(user, password)

# Check command line arguments
if len(sys.argv) > 1:
    post = client.send_post(sys.argv[1], langs=['en-US'])
    print(post)
    #print(f'{user} sez "{sys.argv[1]}"')
else:
    # Otherwise, display usage
    print(f"Usage: {sys.argv[0]} <string>")

**Comment by s-ivr** [comment]
Yep. _sigh_ I think it's escaping my \n making them \\n. sorry to have bothered you. 😳

**Comment by MarshalX** [comment]
That's cool that you found why it happens! Could we close since this is not SDK issue?

**Comment by s-ivr** [comment]
Totally, sorry I should have done that! Doing it now.
________________________________

**Comment by s-ivr** [comment]
Closed! Thanks again!
