### ISSUE TITLE
upload_blob does not currently work due to */* encoding

### ISSUE THREAD

**Issue by DGaffney** [MarshalX/atproto#454]
Right now I'm trying to upload an image to attach it to a feed as follows (assume self.client here is an atproto.Client instance):

```python
    def upload_image(self, image_path):
        # Open the image and resize it to 100x100
        with Image.open(image_path) as img:
            img = img.resize((100, 100), Image.Resampling.LANCZOS)
            # Convert the image to PNG format and save to a buffer
            buffer = io.BytesIO()
            img.save(buffer, format="PNG")  # Force PNG format
            buffer.seek(0)
            # Explicitly specify the MIME type as 'image/png'
            content_type = "image/png"
            # Upload the image
            data = buffer.read()
            response = self.client.upload_blob({
                'data': data,
            })
            return response.blob

```
This reliably fails no matter _what_ transformations I apply to the file. 
```
atproto_client.exceptions.BadRequestError: Response(success=False, status_code=400, content=XrpcError(error='InvalidMimeType', message='Wrong type of file. It is */* but it must match image/png,image/jpeg.'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'ratelimit-limit': '5000', 'ratelimit-remaining': '4984', 'ratelimit-reset': '1732304160', 'ratelimit-policy': '5000;w=3600', 'content-type': 'application/json; charset=utf-8', 'content-length': '109', 'etag': 'W/"6d-gUcY4DPgYN+iCeoV5v5OQKKkymA"', 'date': 'Fri, 22 Nov 2024 18:50:53 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})
```

I believe it it because in [sync_ns](https://github.com/MarshalX/atproto/blob/d030829488ab34ca4e601021e18ec2191f1f77ff/packages/atproto_client/namespaces/sync_ns.py#L5284), we have an encoding of `*/*` asserted. When I manually assert `image/jpeg`, it works. We need to be able to insert a content_type in order for this to work with current spec of the Bsky servers - @MarshalX if you give me the gist of how to add this piping through I can take a shot at it.

**Comment by MarshalX** [comment]
What if you will not set content type for blob? And just curiosity. Why do you set it? The backend should set it automatically. And */* should pass

**Comment by DGaffney** [comment]
At first I was not setting a type, and it was still failing - so I tried to explicitly set a type, and it still fails.

**Comment by MarshalX** [comment]
@DGaffney why do you pass dict to `upload_blob`? You should just pass bytes data of the img

**Comment by DGaffney** [comment]
lol there it is - @MarshalX thank you as usual
