### ISSUE TITLE
get other user's likes?

### ISSUE THREAD

**Issue by Badtz13** [MarshalX/atproto#473]
I've seen that the spec includes the ability to get the likes of other users, however I don't think that this library allows for this. Is this an intentional design choice?

here is a working python http implementation for reference:

```python3
def fetch_likes(profile, reverse=False):
    endpoint = "https://bsky.social/xrpc/com.atproto.repo.listRecords"
    params = {
        'repo': profile,
        'collection': "app.bsky.feed.like",
        'limit': 25,
        'reverse': reverse
    }

    response = requests.get(endpoint, params=params)
    return response.json()

**Comment by MarshalX** [comment]
https://atproto.blue/en/latest/atproto_client/namespace.html#atproto_client.namespaces.sync_ns.AppBskyFeedLikeRecord.list? 

```python
from atproto import Client

client = Client()
likes = client.app.bsky.feed.like.list(profile, limit=25, reverse=True)
print(likes)
```
