### ISSUE TITLE
Work with custom pds?

### ISSUE THREAD

**Issue by numbertheory** [MarshalX/atproto#474]
I tried to use the library to post from a custom domain and my personal data server:

```
from atproto import Client

client = Client()
client.login('pds.my.domain', 'my-app-password')
post = client.send_post('Hello world! I posted this via the Python SDK.')
```
But the response was an error:

```
    raise exceptions.UnauthorizedError(error_response)
atproto_client.exceptions.UnauthorizedError: Response(success=False, status_code=401,
content=XrpcError(error='AuthenticationRequired', message='Invalid identifier or password'), headers={'date': 'Fri, 29 Nov 2024
03:39:37 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '77', 'connection': 'keep-alive', 'x-powered-by':
'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '30', 'ratelimit-remaining': '29', 'ratelimit-reset': '1732851877', 'ratelimit
policy': '30;w=300', 'etag': 'W/"4d-98r3hvgolnybv7tgksQiZbSE7Zg"', 'vary': 'Accept-Encoding'})
```

But, it did work using my standard `bsky.social` account (and appropriate app password). Is there something else that needs to be set when working with custom domains and [personal data servers](https://github.com/bluesky-social/pds)?

I was able to use just requests to accomplish this,[ using this as a guide](https://docs.bsky.app/docs/advanced-guides/posts), but it would be nice to have a library for it.

**Comment by MarshalX** [comment]
You need to pass your PDS url to the Client's constructor

**Comment by numbertheory** [comment]
Oh, I see, I was trying to use a named inputs before, like `Client(pds_endpoint="blah")`. This works

```
from atproto import Client

client = Client("https://pds.site.domain")
client.login('user.name', 'app-password')
post = client.send_post('Hello world! I posted this via the Python SDK.')
```
