### ISSUE TITLE
send_image and send_images should support aspect ratio parameter

### ISSUE THREAD

**Issue by palmer-cl** [MarshalX/atproto#475]
It looks like there was a break in the UI causing images sent via api (not the web client) to use a fallback aspect ratio and object-cover causing different size aspect ratios to render incorrectly: 

![image](https://github.com/user-attachments/assets/4ba72c6d-84c2-4806-b961-be1fb41b38c2)

When you post through the web client, an aspectRatio is set:

![image](https://github.com/user-attachments/assets/9fc03e47-f621-4242-8857-00e5c5127bbc)

Should the send_image function include the ability to set aspect ratio?

![image](https://github.com/user-attachments/assets/17a84bf5-5b95-40a2-b074-d763be928ee9)

**Comment by palmer-cl** [comment]
Related pull request: https://github.com/bluesky-social/social-app/pull/6828

**Comment by ulrischa** [comment]
Huge issues caused by this breaking api change

**Comment by palmer-cl** [comment]
@MarshalX can i get permissions to push? I have an MR to fix this.
