### ISSUE TITLE
Pydantic version question

### ISSUE THREAD

**Issue by kj4lxc** [MarshalX/atproto#482]
Hello all and hope all is well.  I have a dependency question.  I am currently working on a custom integration for home assistant and when trying to import/install atproto im getting a version error about pydantic.  Atproto requests pydantic = ">=2.7,<3" but home assistant itself is using greater than 3 so it will not let me import.  I was wondering about this as I know you have the limit for a reason.  Without this library I am limited to just running basic web calls by hand and they are getting me nowhere.  If I'm being dumb and missed where this was discussed just point me in the right direction!  Thanks!

**Comment by MarshalX** [comment]
Hello pydantic v3 does not exist. The latest release is 2.10.3. Versions history: https://pypi.org/project/pydantic/#history

What the exact issue do you have?

**Comment by kj4lxc** [comment]
Okay so I feel like an idiot.... I FINALLY got into the container that has all of the python libraries in them and found that the install that home assistant pulled was corrupted  I manually removed it and then tried again and now everything is running and importing correctly.  I'm sorry I wasted your time friend!
