### ISSUE TITLE
httpcore throwing error -> "ModuleNotFoundError: No module named 'httpcore.backends'"

### ISSUE THREAD

**Issue by joelghill** [MarshalX/atproto#83]
Looks like [httpcore changed the location of httpcore.backends in v0.17.3](https://stackoverflow.com/questions/76622675/python3-no-module-named-httpcore-backends)

**Comment by MarshalX** [comment]
Thank you! Please run `pip install -U atproto`. The fixed version is 0.0.17. If you downgraded `httpcore` please upgrade back.
