### ISSUE TITLE
Fails to add atproto via Replit due to dependency version conflict

### ISSUE THREAD

**Issue by hensonb3** [MarshalX/atproto#89]
Replit: Updating package configuration

--> poetry add 'atproto 0.0.17'

Updating dependencies
Resolving dependencies...

  SolverProblemError

  Because no versions of replit match >3.2.4,<3.2.5 || >3.2.5,<3.2.6 || >3.2.6,<3.2.7 || >3.2.7,<3.2.8 || >3.2.8,<3.3.0 || >3.3.0,<3.3.1 || >3.3.1,<4.0.0
   and replit (3.2.4) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<3.2.5 || >3.2.5,<3.2.6 || >3.2.6,<3.2.7 || >3.2.7,<3.2.8 || >3.2.8,<3.3.0 || >3.3.0,<3.3.1 || >3.3.1,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.2.6) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<3.2.5 || >3.2.5,<3.2.7 || >3.2.7,<3.2.8 || >3.2.8,<3.3.0 || >3.3.0,<3.3.1 || >3.3.1,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.2.7) depends on typing_extensions (>=3.7.4,<4.0.0)
   and replit (3.2.8) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<3.2.5 || >3.2.5,<3.3.0 || >3.3.0,<3.3.1 || >3.3.1,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.3.0) depends on typing_extensions (>=3.7.4,<4.0.0)
   and replit (3.3.1) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<3.2.5 || >3.2.5,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.2.5) depends on typing_extensions (>=3.7.4,<4.0.0)
   and atproto (0.0.17) depends on typing-extensions (>=4.5.0,<4.6.0), atproto (0.0.17) is incompatible with replit (>=3.2.4,<4.0.0).
  So, because python-template depends on both replit (^3.2.4) and atproto (0.0.17), version solving failed.

  at venv/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
exit status 1

Replit: Package operation failed.

**Comment by hensonb3** [comment]
I suppose I don't need the replit package to run a simple Python script in replit. So I removed the replit package and it's dependencies, including typing-extensions (3.10.0.2) and installed atproto

**Comment by MarshalX** [comment]
Hi. I'll check if is it possible to lower the version of typing extensions in atproto

**Comment by MarshalX** [comment]
fixed in v0.0.18
