### ISSUE TITLE
Ability to set language or prevent "Translate this post" appearing

### ISSUE THREAD

**Issue by hensonb3** [MarshalX/atproto#94]
![IMG_8694](https://github.com/MarshalX/atproto/assets/50562920/f821d79f-4f00-45e8-bea3-3525bf2e9fe1)

**Comment by hensonb3** [comment]
Tried to ask in Discord and try:
bluesky_client.send_post(text=final_score_text, langs=['en'])

Getting below error:
TypeError: Client.send_post() got unexpected keyword arguments 'langs'

**Comment by MarshalX** [comment]
added in https://github.com/MarshalX/atproto/pull/96. Will be included in the next release (v0.0.19)
